import os

DB_ERROR_STR = "DB error"
REQ_ERROR_STR = "Requests error"

GATEWAY_URL = os.environ["GATEWAY_URL"]
PAYMENT_INTERNAL_URL = os.environ["PAYMENT_INTERNAL_URL"].rstrip("/")
STOCK_INTERNAL_URL = os.environ["STOCK_INTERNAL_URL"].rstrip("/")
CHECKOUT_PROTOCOL = os.environ.get("CHECKOUT_PROTOCOL", "saga").strip().lower()
VALID_CHECKOUT_PROTOCOLS = {"saga", "2pc"}

ORDER_LOCK_TTL_SECONDS = int(os.environ.get("ORDER_LOCK_TTL_SECONDS", "30"))
REQUEST_TIMEOUT_SECONDS = int(os.environ.get("REQUEST_TIMEOUT_SECONDS", "3"))
RECENT_CHECKOUT_TTL_SECONDS = int(os.environ.get("RECENT_CHECKOUT_TTL_SECONDS", "2"))

ORDER_LOCK_KEY_PREFIX = "checkout_lock:"
TX_KEY_PREFIX = "checkout_tx:"
ORDER_ACTIVE_TX_PREFIX = "checkout_order_active_tx:"
ORDER_RECENT_CHECKOUT_PREFIX = "checkout_order_recent:"
ORDER_COMMIT_FENCE_PREFIX = "checkout_order_commit_fence:"

STATUS_INIT = "INIT"
STATUS_SAGA_STOCK_RESERVED = "SAGA_STOCK_RESERVED"
STATUS_SAGA_PAYMENT_CHARGED = "SAGA_PAYMENT_CHARGED"
STATUS_SAGA_COMPENSATING = "SAGA_COMPENSATING"
STATUS_2PC_PREPARING = "2PC_PREPARING"
STATUS_2PC_PREPARED = "2PC_PREPARED"
STATUS_2PC_ABORTING = "2PC_ABORTING"
STATUS_2PC_COMMITTING = "2PC_COMMITTING"
STATUS_2PC_FINALIZATION_PENDING = "2PC_FINALIZATION_PENDING"
STATUS_ABORTED = "ABORTED"
STATUS_COMPLETED = "COMPLETED"
STATUS_FAILED_NEEDS_RECOVERY = "FAILED_NEEDS_RECOVERY"
TERMINAL_TX_STATUSES = {
    STATUS_ABORTED,
    STATUS_COMPLETED,
    STATUS_FAILED_NEEDS_RECOVERY,
    STATUS_2PC_FINALIZATION_PENDING,
}

DECISION_COMMIT = "COMMIT"
DECISION_ABORT = "ABORT"

REDIS_HOST = os.environ["REDIS_HOST"]
REDIS_PORT = int(os.environ["REDIS_PORT"])
REDIS_PASSWORD = os.environ["REDIS_PASSWORD"]
REDIS_DB = int(os.environ["REDIS_DB"])


if CHECKOUT_PROTOCOL not in VALID_CHECKOUT_PROTOCOLS:
    raise RuntimeError(
        f"Invalid CHECKOUT_PROTOCOL '{CHECKOUT_PROTOCOL}'. "
        "Expected one of: saga, 2pc"
    )

