apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment
          image: ttl.sh/dds26-1-payment:24h
          imagePullPolicy: IfNotPresent
          command: ["gunicorn", "-b", "0.0.0.0:5000", "-w", "8", "-c", "gunicorn.conf.py", "--timeout", "30", "--log-level=info", "app:app"]
          resources:
            requests:
              cpu: "300m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "1Gi"
          ports:
            - containerPort: 5000
          env:
            - name: ORDER_SERVICE_URL
              value: "http://order-service:5000"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
            - name: PARTICIPANT_CONSUMER_PREFETCH_COUNT
              value: "8"
            - name: CHECKOUT_PROTOCOL
              value: "saga"
            - name: REDIS_HOST
              value: "payment-db"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "redis"
            - name: REDIS_DB
              value: "0"
