auth:
  password: redis
master:
  persistence:
    size: 4Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 1000m
replica:
  replicaCount: 1
  persistence:
    size: 4Gi
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 2Gi
      cpu: 1000m
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPU: "70"
    targetMemory: "80"
